# fly.toml app configuration file generated for musique on 2024-08-20T13:28:41+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'musique'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
